package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name="accion"
    ,catalog="db_laboratorio"
)
public class Accion  implements java.io.Serializable {


     private Integer idAccion;
     private String descripcion;
     private Set<RolesAccion> rolesAccions = new HashSet<RolesAccion>(0);

    public Accion() {
    }

    public Accion(String descripcion, Set<RolesAccion> rolesAccions) {
       this.descripcion = descripcion;
       this.rolesAccions = rolesAccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_accion", unique=true, nullable=false)
    public Integer getIdAccion() {
        return this.idAccion;
    }
    
    public void setIdAccion(Integer idAccion) {
        this.idAccion = idAccion;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="accion")
    public Set<RolesAccion> getRolesAccions() {
        return this.rolesAccions;
    }
    
    public void setRolesAccions(Set<RolesAccion> rolesAccions) {
        this.rolesAccions = rolesAccions;
    }




}


