package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name="clase"
    ,catalog="db_laboratorio"
)
public class Clase  implements java.io.Serializable {


     private Integer idClase;
     private Grupo grupo;
     private String descripcion;
     private Character estado;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Clase() {
    }

    public Clase(Grupo grupo, String descripcion, Character estado, Set<Examen> examens) {
       this.grupo = grupo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.examens = examens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_clase", unique=true, nullable=false)
    public Integer getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(Integer idClase) {
        this.idClase = idClase;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_grupo")
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    
    @Column(name="descripcion", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="clase")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


