package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name="clase"
    ,catalog="db_laboratorio"
)
public class Clase  implements java.io.Serializable {


     private Integer idClase;
     private Integer codGrupo;
     private String desClase;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Clase() {
    }

    public Clase(Integer codGrupo, String desClase, Set<Examen> examens) {
       this.codGrupo = codGrupo;
       this.desClase = desClase;
       this.examens = examens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IdClase", unique=true, nullable=false)
    public Integer getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(Integer idClase) {
        this.idClase = idClase;
    }
    
    @Column(name="CodGrupo")
    public Integer getCodGrupo() {
        return this.codGrupo;
    }
    
    public void setCodGrupo(Integer codGrupo) {
        this.codGrupo = codGrupo;
    }
    
    @Column(name="DesClase", length=80)
    public String getDesClase() {
        return this.desClase;
    }
    
    public void setDesClase(String desClase) {
        this.desClase = desClase;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="clase")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


