package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="db_laboratorio"
)
public class Cliente  implements java.io.Serializable {


     private String codCliente;
     private Integer tipoCodCliente;
     private String apepat;
     private String apemat;
     private String nombres;
     private Date fechaNac;
     private String direccion;
     private String sexo;

    public Cliente() {
    }

	
    public Cliente(String codCliente) {
        this.codCliente = codCliente;
    }
    public Cliente(String codCliente, Integer tipoCodCliente, String apepat, String apemat, String nombres, Date fechaNac, String direccion, String sexo) {
       this.codCliente = codCliente;
       this.tipoCodCliente = tipoCodCliente;
       this.apepat = apepat;
       this.apemat = apemat;
       this.nombres = nombres;
       this.fechaNac = fechaNac;
       this.direccion = direccion;
       this.sexo = sexo;
    }
   
     @Id 
    
    @Column(name="cod_cliente", unique=true, nullable=false, length=11)
    public String getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(String codCliente) {
        this.codCliente = codCliente;
    }
    
    @Column(name="tipo_cod_cliente")
    public Integer getTipoCodCliente() {
        return this.tipoCodCliente;
    }
    
    public void setTipoCodCliente(Integer tipoCodCliente) {
        this.tipoCodCliente = tipoCodCliente;
    }
    
    @Column(name="apepat", length=45)
    public String getApepat() {
        return this.apepat;
    }
    
    public void setApepat(String apepat) {
        this.apepat = apepat;
    }
    
    @Column(name="apemat", length=45)
    public String getApemat() {
        return this.apemat;
    }
    
    public void setApemat(String apemat) {
        this.apemat = apemat;
    }
    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nac", length=10)
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    
    @Column(name="direccion", length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


