package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="db_laboratorio"
)
public class Departamento  implements java.io.Serializable {


     private int codDepa;
     private String desDepa;
     private String codSup;
     private float latitud;
     private float longitud;

    public Departamento() {
    }

    public Departamento(int codDepa, String desDepa, String codSup, float latitud, float longitud) {
       this.codDepa = codDepa;
       this.desDepa = desDepa;
       this.codSup = codSup;
       this.latitud = latitud;
       this.longitud = longitud;
    }
   
     @Id 
    
    @Column(name="cod_depa", unique=true, nullable=false)
    public int getCodDepa() {
        return this.codDepa;
    }
    
    public void setCodDepa(int codDepa) {
        this.codDepa = codDepa;
    }
    
    @Column(name="des_depa", nullable=false, length=80)
    public String getDesDepa() {
        return this.desDepa;
    }
    
    public void setDesDepa(String desDepa) {
        this.desDepa = desDepa;
    }
    
    @Column(name="cod_sup", nullable=false, length=45)
    public String getCodSup() {
        return this.codSup;
    }
    
    public void setCodSup(String codSup) {
        this.codSup = codSup;
    }
    
    @Column(name="latitud", nullable=false, precision=12, scale=0)
    public float getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(float latitud) {
        this.latitud = latitud;
    }
    
    @Column(name="longitud", nullable=false, precision=12, scale=0)
    public float getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(float longitud) {
        this.longitud = longitud;
    }




}


