package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetPerfil generated by hbm2java
 */
@Entity
@Table(name="det_perfil"
    ,catalog="db_laboratorio"
)
public class DetPerfil  implements java.io.Serializable {


     private String codPerfil;
     private Examen examen;
     private Character estado;

    public DetPerfil() {
    }

	
    public DetPerfil(String codPerfil, Examen examen) {
        this.codPerfil = codPerfil;
        this.examen = examen;
    }
    public DetPerfil(String codPerfil, Examen examen, Character estado) {
       this.codPerfil = codPerfil;
       this.examen = examen;
       this.estado = estado;
    }
   
     @Id 
    
    @Column(name="cod_perfil", unique=true, nullable=false, length=10)
    public String getCodPerfil() {
        return this.codPerfil;
    }
    
    public void setCodPerfil(String codPerfil) {
        this.codPerfil = codPerfil;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_examen", nullable=false)
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


