package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * DetVenta generated by hbm2java
 */
@Entity
@Table(name="det_venta"
    ,catalog="db_laboratorio"
    , uniqueConstraints = @UniqueConstraint(columnNames="cod_examen") 
)
public class DetVenta  implements java.io.Serializable {


     private Integer idDetVenta;
     private Venta venta;
     private Examen examen;
     private BigDecimal cantidad;
     private BigDecimal dscto;
     private Character estado;
     private Character estadoProceso;
     private Date fechaAtencion;
     private BigDecimal precio;

    public DetVenta() {
    }

	
    public DetVenta(Venta venta, Examen examen, BigDecimal cantidad, BigDecimal dscto) {
        this.venta = venta;
        this.examen = examen;
        this.cantidad = cantidad;
        this.dscto = dscto;
    }
    public DetVenta(Venta venta, Examen examen, BigDecimal cantidad, BigDecimal dscto, Character estado, Character estadoProceso, Date fechaAtencion, BigDecimal precio) {
       this.venta = venta;
       this.examen = examen;
       this.cantidad = cantidad;
       this.dscto = dscto;
       this.estado = estado;
       this.estadoProceso = estadoProceso;
       this.fechaAtencion = fechaAtencion;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_det_venta", unique=true, nullable=false)
    public Integer getIdDetVenta() {
        return this.idDetVenta;
    }
    
    public void setIdDetVenta(Integer idDetVenta) {
        this.idDetVenta = idDetVenta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_comp_venta", nullable=false)
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_examen", unique=true, nullable=false)
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    
    @Column(name="cantidad", nullable=false, precision=9)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="dscto", nullable=false, precision=9)
    public BigDecimal getDscto() {
        return this.dscto;
    }
    
    public void setDscto(BigDecimal dscto) {
        this.dscto = dscto;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    
    @Column(name="estado_proceso", length=1)
    public Character getEstadoProceso() {
        return this.estadoProceso;
    }
    
    public void setEstadoProceso(Character estadoProceso) {
        this.estadoProceso = estadoProceso;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_atencion", length=19)
    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    
    @Column(name="precio", precision=9)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


