package com.raitcon.hibernate.bean;
// Generated 23/04/2016 11:00:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name="distrito"
    ,catalog="db_laboratorio"
)
public class Distrito  implements java.io.Serializable {


     private int codDistrito;
     private Provincia provincia;
     private String desDistrito;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);
     private Set<Paciente> pacientes_1 = new HashSet<Paciente>(0);

    public Distrito() {
    }

	
    public Distrito(int codDistrito, Provincia provincia, String desDistrito) {
        this.codDistrito = codDistrito;
        this.provincia = provincia;
        this.desDistrito = desDistrito;
    }
    public Distrito(int codDistrito, Provincia provincia, String desDistrito, Set<Paciente> pacientes, Set<Paciente> pacientes_1) {
       this.codDistrito = codDistrito;
       this.provincia = provincia;
       this.desDistrito = desDistrito;
       this.pacientes = pacientes;
       this.pacientes_1 = pacientes_1;
    }
   
     @Id 
    
    @Column(name="cod_distrito", unique=true, nullable=false)
    public int getCodDistrito() {
        return this.codDistrito;
    }
    
    public void setCodDistrito(int codDistrito) {
        this.codDistrito = codDistrito;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_provincia", nullable=false)
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    
    @Column(name="des_distrito", nullable=false, length=100)
    public String getDesDistrito() {
        return this.desDistrito;
    }
    
    public void setDesDistrito(String desDistrito) {
        this.desDistrito = desDistrito;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="distrito")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="distrito")
    public Set<Paciente> getPacientes_1() {
        return this.pacientes_1;
    }
    
    public void setPacientes_1(Set<Paciente> pacientes_1) {
        this.pacientes_1 = pacientes_1;
    }




}


