package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:53:11 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Distrito generated by hbm2java
 */
@Entity
@Table(name="distrito"
    ,catalog="db_laboratorio"
)
public class Distrito  implements java.io.Serializable {


     private int codDistrito;
     private Provincia provincia;
     private String desDistrito;

    public Distrito() {
    }

    public Distrito(int codDistrito, Provincia provincia, String desDistrito) {
       this.codDistrito = codDistrito;
       this.provincia = provincia;
       this.desDistrito = desDistrito;
    }
   
     @Id 
    
    @Column(name="cod_distrito", unique=true, nullable=false)
    public int getCodDistrito() {
        return this.codDistrito;
    }
    
    public void setCodDistrito(int codDistrito) {
        this.codDistrito = codDistrito;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_provincia", nullable=false)
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    
    @Column(name="des_distrito", nullable=false, length=100)
    public String getDesDistrito() {
        return this.desDistrito;
    }
    
    public void setDesDistrito(String desDistrito) {
        this.desDistrito = desDistrito;
    }




}


