package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DtExamenInsumo generated by hbm2java
 */
@Entity
@Table(name="dt_examen_insumo"
    ,catalog="db_laboratorio"
)
public class DtExamenInsumo  implements java.io.Serializable {


     private DtExamenInsumoId id;
     private Insumo insumo;
     private Examen examen;
     private int idDtExaIns;
     private BigDecimal cantidad;
     private BigDecimal precio;

    public DtExamenInsumo() {
    }

	
    public DtExamenInsumo(DtExamenInsumoId id, Insumo insumo, Examen examen, int idDtExaIns) {
        this.id = id;
        this.insumo = insumo;
        this.examen = examen;
        this.idDtExaIns = idDtExaIns;
    }
    public DtExamenInsumo(DtExamenInsumoId id, Insumo insumo, Examen examen, int idDtExaIns, BigDecimal cantidad, BigDecimal precio) {
       this.id = id;
       this.insumo = insumo;
       this.examen = examen;
       this.idDtExaIns = idDtExaIns;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="codInsumo", column=@Column(name="cod_insumo", nullable=false, length=10) ), 
        @AttributeOverride(name="codExamen", column=@Column(name="cod_examen", nullable=false, length=10) ) } )
    public DtExamenInsumoId getId() {
        return this.id;
    }
    
    public void setId(DtExamenInsumoId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_insumo", nullable=false, insertable=false, updatable=false)
    public Insumo getInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(Insumo insumo) {
        this.insumo = insumo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_examen", nullable=false, insertable=false, updatable=false)
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    
    @Column(name="id_dt_exa_ins", nullable=false)
    public int getIdDtExaIns() {
        return this.idDtExaIns;
    }
    
    public void setIdDtExaIns(int idDtExaIns) {
        this.idDtExaIns = idDtExaIns;
    }
    
    @Column(name="cantidad", precision=9)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="precio", precision=9)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


