package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estacivil generated by hbm2java
 */
@Entity
@Table(name="estacivil"
    ,catalog="db_laboratorio"
)
public class Estacivil  implements java.io.Serializable {


     private Integer codEstacivil;
     private String descripcion;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);

    public Estacivil() {
    }

    public Estacivil(String descripcion, Set<Paciente> pacientes) {
       this.descripcion = descripcion;
       this.pacientes = pacientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="cod_estacivil", unique=true, nullable=false)
    public Integer getCodEstacivil() {
        return this.codEstacivil;
    }
    
    public void setCodEstacivil(Integer codEstacivil) {
        this.codEstacivil = codEstacivil;
    }
    
    @Column(name="descripcion", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estacivil")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }




}


