package com.raitcon.hibernate.bean;
// Generated 23/04/2016 06:58:33 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estudio generated by hbm2java
 */
@Entity
@Table(name="estudio"
    ,catalog="db_laboratorio"
)
public class Estudio  implements java.io.Serializable {


     private int idEstudio;
     private Examen examen;
     private String descripcion;
     private Character estado;
     private Set<Prueba> pruebas = new HashSet<Prueba>(0);

    public Estudio() {
    }

	
    public Estudio(int idEstudio, Examen examen) {
        this.idEstudio = idEstudio;
        this.examen = examen;
    }
    public Estudio(int idEstudio, Examen examen, String descripcion, Character estado, Set<Prueba> pruebas) {
       this.idEstudio = idEstudio;
       this.examen = examen;
       this.descripcion = descripcion;
       this.estado = estado;
       this.pruebas = pruebas;
    }
   
     @Id 
    
    @Column(name="id_estudio", unique=true, nullable=false)
    public int getIdEstudio() {
        return this.idEstudio;
    }
    
    public void setIdEstudio(int idEstudio) {
        this.idEstudio = idEstudio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_examen", nullable=false)
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    
    @Column(name="descripcion", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estudio")
    public Set<Prueba> getPruebas() {
        return this.pruebas;
    }
    
    public void setPruebas(Set<Prueba> pruebas) {
        this.pruebas = pruebas;
    }




}


