package com.raitcon.hibernate.bean;
// Generated 23/04/2016 06:58:33 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name="examen"
    ,catalog="db_laboratorio"
    , uniqueConstraints = @UniqueConstraint(columnNames="idexamen") 
)
public class Examen  implements java.io.Serializable {


     private String codExamen;
     private Clase claseByIdClase;
     private Clase claseByIdClase_1;
     private TipoExamen tipoExamen;
     private String descripcion;
     private String enlace;
     private BigDecimal precio;
     private Integer idexamen;
     private Set<DetVenta> detVentas = new HashSet<DetVenta>(0);
     private Set<Estudio> estudios = new HashSet<Estudio>(0);

    public Examen() {
    }

	
    public Examen(String codExamen, Clase claseByIdClase_1) {
        this.codExamen = codExamen;
        this.claseByIdClase_1 = claseByIdClase_1;
    }
    public Examen(String codExamen, Clase claseByIdClase, Clase claseByIdClase_1, TipoExamen tipoExamen, String descripcion, String enlace, BigDecimal precio, Integer idexamen, Set<DetVenta> detVentas, Set<Estudio> estudios) {
       this.codExamen = codExamen;
       this.claseByIdClase = claseByIdClase;
       this.claseByIdClase_1 = claseByIdClase_1;
       this.tipoExamen = tipoExamen;
       this.descripcion = descripcion;
       this.enlace = enlace;
       this.precio = precio;
       this.idexamen = idexamen;
       this.detVentas = detVentas;
       this.estudios = estudios;
    }
   
     @Id 
    
    @Column(name="cod_examen", unique=true, nullable=false, length=10)
    public String getCodExamen() {
        return this.codExamen;
    }
    
    public void setCodExamen(String codExamen) {
        this.codExamen = codExamen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdClase")
    public Clase getClaseByIdClase() {
        return this.claseByIdClase;
    }
    
    public void setClaseByIdClase(Clase claseByIdClase) {
        this.claseByIdClase = claseByIdClase;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_clase", nullable=false)
    public Clase getClaseByIdClase_1() {
        return this.claseByIdClase_1;
    }
    
    public void setClaseByIdClase_1(Clase claseByIdClase_1) {
        this.claseByIdClase_1 = claseByIdClase_1;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_examen")
    public TipoExamen getTipoExamen() {
        return this.tipoExamen;
    }
    
    public void setTipoExamen(TipoExamen tipoExamen) {
        this.tipoExamen = tipoExamen;
    }
    
    @Column(name="descripcion", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="enlace", length=20)
    public String getEnlace() {
        return this.enlace;
    }
    
    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }
    
    @Column(name="precio", precision=9)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    
    @Column(name="idexamen", unique=true)
    public Integer getIdexamen() {
        return this.idexamen;
    }
    
    public void setIdexamen(Integer idexamen) {
        this.idexamen = idexamen;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="examen")
    public Set<DetVenta> getDetVentas() {
        return this.detVentas;
    }
    
    public void setDetVentas(Set<DetVenta> detVentas) {
        this.detVentas = detVentas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="examen")
    public Set<Estudio> getEstudios() {
        return this.estudios;
    }
    
    public void setEstudios(Set<Estudio> estudios) {
        this.estudios = estudios;
    }




}


