package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name="examen"
    ,catalog="db_laboratorio"
)
public class Examen  implements java.io.Serializable {


     private int idexamen;
     private Clase clase;
     private String descripcion;
     private BigDecimal precio;
     private Set<DetalleExamen> detalleExamens = new HashSet<DetalleExamen>(0);

    public Examen() {
    }

	
    public Examen(int idexamen, Clase clase) {
        this.idexamen = idexamen;
        this.clase = clase;
    }
    public Examen(int idexamen, Clase clase, String descripcion, BigDecimal precio, Set<DetalleExamen> detalleExamens) {
       this.idexamen = idexamen;
       this.clase = clase;
       this.descripcion = descripcion;
       this.precio = precio;
       this.detalleExamens = detalleExamens;
    }
   
     @Id 
    
    @Column(name="idexamen", unique=true, nullable=false)
    public int getIdexamen() {
        return this.idexamen;
    }
    
    public void setIdexamen(int idexamen) {
        this.idexamen = idexamen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdClase", nullable=false)
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    
    @Column(name="descripcion", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="precio", precision=12)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="examen")
    public Set<DetalleExamen> getDetalleExamens() {
        return this.detalleExamens;
    }
    
    public void setDetalleExamens(Set<DetalleExamen> detalleExamens) {
        this.detalleExamens = detalleExamens;
    }




}


