package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistorialPaciente generated by hbm2java
 */
@Entity
@Table(name="historial_paciente"
    ,catalog="db_laboratorio"
)
public class HistorialPaciente  implements java.io.Serializable {


     private Integer idHistorialPaciente;
     private String codPaciente;
     private String descPaciente;
     private String codVenta;
     private Date fechaAtencion;
     private Date fechaIngreso;
     private String codExamen;
     private String descExamen;
     private String codPersonal;
     private String descPersonal;
     private Character estado;

    public HistorialPaciente() {
    }

    public HistorialPaciente(String codPaciente, String descPaciente, String codVenta, Date fechaAtencion, Date fechaIngreso, String codExamen, String descExamen, String codPersonal, String descPersonal, Character estado) {
       this.codPaciente = codPaciente;
       this.descPaciente = descPaciente;
       this.codVenta = codVenta;
       this.fechaAtencion = fechaAtencion;
       this.fechaIngreso = fechaIngreso;
       this.codExamen = codExamen;
       this.descExamen = descExamen;
       this.codPersonal = codPersonal;
       this.descPersonal = descPersonal;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_historial_paciente", unique=true, nullable=false)
    public Integer getIdHistorialPaciente() {
        return this.idHistorialPaciente;
    }
    
    public void setIdHistorialPaciente(Integer idHistorialPaciente) {
        this.idHistorialPaciente = idHistorialPaciente;
    }
    
    @Column(name="cod_paciente", length=16)
    public String getCodPaciente() {
        return this.codPaciente;
    }
    
    public void setCodPaciente(String codPaciente) {
        this.codPaciente = codPaciente;
    }
    
    @Column(name="desc_paciente", length=200)
    public String getDescPaciente() {
        return this.descPaciente;
    }
    
    public void setDescPaciente(String descPaciente) {
        this.descPaciente = descPaciente;
    }
    
    @Column(name="cod_venta", length=16)
    public String getCodVenta() {
        return this.codVenta;
    }
    
    public void setCodVenta(String codVenta) {
        this.codVenta = codVenta;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_atencion", length=19)
    public Date getFechaAtencion() {
        return this.fechaAtencion;
    }
    
    public void setFechaAtencion(Date fechaAtencion) {
        this.fechaAtencion = fechaAtencion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", length=19)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    
    @Column(name="cod_examen", length=10)
    public String getCodExamen() {
        return this.codExamen;
    }
    
    public void setCodExamen(String codExamen) {
        this.codExamen = codExamen;
    }
    
    @Column(name="desc_examen", length=100)
    public String getDescExamen() {
        return this.descExamen;
    }
    
    public void setDescExamen(String descExamen) {
        this.descExamen = descExamen;
    }
    
    @Column(name="cod_personal", length=16)
    public String getCodPersonal() {
        return this.codPersonal;
    }
    
    public void setCodPersonal(String codPersonal) {
        this.codPersonal = codPersonal;
    }
    
    @Column(name="desc_personal", length=45)
    public String getDescPersonal() {
        return this.descPersonal;
    }
    
    public void setDescPersonal(String descPersonal) {
        this.descPersonal = descPersonal;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


