package com.raitcon.hibernate.bean;
// Generated 08/04/2016 10:38:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instruccion generated by hbm2java
 */
@Entity
@Table(name="instruccion"
    ,catalog="db_laboratorio"
)
public class Instruccion  implements java.io.Serializable {


     private int codInstruccion;
     private String descripcion;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);
 ;

    public Instruccion() {
    }

	
    public Instruccion(int codInstruccion) {
        this.codInstruccion = codInstruccion;
    }
    public Instruccion(int codInstruccion, String descripcion, Set<Paciente> pacientes) {
       this.codInstruccion = codInstruccion;
       this.descripcion = descripcion;
       this.pacientes = pacientes;
     
    }
   
     @Id 
    
    @Column(name="cod_instruccion", unique=true, nullable=false)
    public int getCodInstruccion() {
        return this.codInstruccion;
    }
    
    public void setCodInstruccion(int codInstruccion) {
        this.codInstruccion = codInstruccion;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="instruccion")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }





}


