package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Insumo generated by hbm2java
 */
@Entity
@Table(name="insumo"
    ,catalog="db_laboratorio"
)
public class Insumo  implements java.io.Serializable {


     private String codInsumo;
     private Almacen almacen;
     private Marca marca;
     private Proveedor proveedor;
     private UnidMedida unidMedida;
     private TipoInsumo tipoInsumo;
     private String codBarras;
     private String descripcion;
     private BigDecimal precio;
     private BigDecimal stockActual;
     private BigDecimal stockMin;
     private String comentarios;
     private BigDecimal stockMax;
     private Set<DtExamenInsumo> dtExamenInsumos = new HashSet<DtExamenInsumo>(0);

    public Insumo() {
    }

	
    public Insumo(String codInsumo, TipoInsumo tipoInsumo) {
        this.codInsumo = codInsumo;
        this.tipoInsumo = tipoInsumo;
    }
    public Insumo(String codInsumo, Almacen almacen, Marca marca, Proveedor proveedor, UnidMedida unidMedida, TipoInsumo tipoInsumo, String codBarras, String descripcion, BigDecimal precio, BigDecimal stockActual, BigDecimal stockMin, String comentarios, BigDecimal stockMax, Set<DtExamenInsumo> dtExamenInsumos) {
       this.codInsumo = codInsumo;
       this.almacen = almacen;
       this.marca = marca;
       this.proveedor = proveedor;
       this.unidMedida = unidMedida;
       this.tipoInsumo = tipoInsumo;
       this.codBarras = codBarras;
       this.descripcion = descripcion;
       this.precio = precio;
       this.stockActual = stockActual;
       this.stockMin = stockMin;
       this.comentarios = comentarios;
       this.stockMax = stockMax;
       this.dtExamenInsumos = dtExamenInsumos;
    }
   
     @Id 
    
    @Column(name="cod_insumo", unique=true, nullable=false, length=10)
    public String getCodInsumo() {
        return this.codInsumo;
    }
    
    public void setCodInsumo(String codInsumo) {
        this.codInsumo = codInsumo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_almacen")
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_marca")
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proveedor")
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_unid_medida")
    public UnidMedida getUnidMedida() {
        return this.unidMedida;
    }
    
    public void setUnidMedida(UnidMedida unidMedida) {
        this.unidMedida = unidMedida;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_insumo", nullable=false)
    public TipoInsumo getTipoInsumo() {
        return this.tipoInsumo;
    }
    
    public void setTipoInsumo(TipoInsumo tipoInsumo) {
        this.tipoInsumo = tipoInsumo;
    }
    
    @Column(name="cod_barras", length=60)
    public String getCodBarras() {
        return this.codBarras;
    }
    
    public void setCodBarras(String codBarras) {
        this.codBarras = codBarras;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="precio", precision=9)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    
    @Column(name="stock_actual", precision=9)
    public BigDecimal getStockActual() {
        return this.stockActual;
    }
    
    public void setStockActual(BigDecimal stockActual) {
        this.stockActual = stockActual;
    }
    
    @Column(name="stock_min", precision=9)
    public BigDecimal getStockMin() {
        return this.stockMin;
    }
    
    public void setStockMin(BigDecimal stockMin) {
        this.stockMin = stockMin;
    }
    
    @Column(name="comentarios", length=100)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    
    @Column(name="stock_max", precision=9)
    public BigDecimal getStockMax() {
        return this.stockMax;
    }
    
    public void setStockMax(BigDecimal stockMax) {
        this.stockMax = stockMax;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="insumo")
    public Set<DtExamenInsumo> getDtExamenInsumos() {
        return this.dtExamenInsumos;
    }
    
    public void setDtExamenInsumos(Set<DtExamenInsumo> dtExamenInsumos) {
        this.dtExamenInsumos = dtExamenInsumos;
    }




}


