package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="db_laboratorio"
)
public class Menu  implements java.io.Serializable {


     private Integer idMenu;
     private String descripcion;
     private Character state;
     private Integer peso;
     private Set<SubMenu> subMenus = new HashSet<SubMenu>(0);
     private Set<RolesAccion> rolesAccions = new HashSet<RolesAccion>(0);

    public Menu() {
    }

    public Menu(String descripcion, Character state, Integer peso, Set<SubMenu> subMenus, Set<RolesAccion> rolesAccions) {
       this.descripcion = descripcion;
       this.state = state;
       this.peso = peso;
       this.subMenus = subMenus;
       this.rolesAccions = rolesAccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_menu", unique=true, nullable=false)
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="state", length=1)
    public Character getState() {
        return this.state;
    }
    
    public void setState(Character state) {
        this.state = state;
    }
    
    @Column(name="peso")
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="menu")
    public Set<SubMenu> getSubMenus() {
        return this.subMenus;
    }
    
    public void setSubMenus(Set<SubMenu> subMenus) {
        this.subMenus = subMenus;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="menu")
    public Set<RolesAccion> getRolesAccions() {
        return this.rolesAccions;
    }
    
    public void setRolesAccions(Set<RolesAccion> rolesAccions) {
        this.rolesAccions = rolesAccions;
    }




}


