package com.raitcon.hibernate.bean;
// Generated 08/04/2016 10:38:47 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ocupacion generated by hbm2java
 */
@Entity
@Table(name="ocupacion"
    ,catalog="db_laboratorio"
)
public class Ocupacion  implements java.io.Serializable {


     private int codOcupacion;
     private String descripcion;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);
     private Set<Paciente> pacientes_1 = new HashSet<Paciente>(0);

    public Ocupacion() {
    }

	
    public Ocupacion(int codOcupacion) {
        this.codOcupacion = codOcupacion;
    }
    public Ocupacion(int codOcupacion, String descripcion, Set<Paciente> pacientes, Set<Paciente> pacientes_1) {
       this.codOcupacion = codOcupacion;
       this.descripcion = descripcion;
       this.pacientes = pacientes;
       this.pacientes_1 = pacientes_1;
    }
   
     @Id 
    
    @Column(name="cod_ocupacion", unique=true, nullable=false)
    public int getCodOcupacion() {
        return this.codOcupacion;
    }
    
    public void setCodOcupacion(int codOcupacion) {
        this.codOcupacion = codOcupacion;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ocupacion")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ocupacion")
    public Set<Paciente> getPacientes_1() {
        return this.pacientes_1;
    }
    
    public void setPacientes_1(Set<Paciente> pacientes_1) {
        this.pacientes_1 = pacientes_1;
    }




}


