package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ocupacion generated by hbm2java
 */
@Entity
@Table(name="ocupacion"
    ,catalog="db_laboratorio"
)
public class Ocupacion  implements java.io.Serializable {


     private int codOcupacion;
     private String descripcion;
     private Set<Personal> personals = new HashSet<Personal>(0);

    public Ocupacion() {
    }

	
    public Ocupacion(int codOcupacion) {
        this.codOcupacion = codOcupacion;
    }
    public Ocupacion(int codOcupacion, String descripcion, Set<Personal> personals) {
       this.codOcupacion = codOcupacion;
       this.descripcion = descripcion;
       this.personals = personals;
    }
   
     @Id 
    
    @Column(name="cod_ocupacion", unique=true, nullable=false)
    public int getCodOcupacion() {
        return this.codOcupacion;
    }
    
    public void setCodOcupacion(int codOcupacion) {
        this.codOcupacion = codOcupacion;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ocupacion")
    public Set<Personal> getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set<Personal> personals) {
        this.personals = personals;
    }




}


