package com.raitcon.hibernate.bean;
// Generated 23/04/2016 11:00:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="db_laboratorio"
)
public class Paciente  implements java.io.Serializable {


     private String codPaciente;
     private TipoPaciente tipoPaciente;
     private Sexo sexo;
     private Estacivil estacivil;
     private Ocupacion ocupacion;
     private Distrito distrito;
     private Instruccion instruccion;
     private String nombre1;
     private String nombre2;
     private String apPaterno;
     private String apMaterno;
     private Date fechaNacimiento;
     private Date fechaIngreso;
     private String direccion;
     private String telefono;
     private String email;
     private byte[] foto;
     private Character estado;
     private String dni;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Paciente() {
    }

	
    public Paciente(String codPaciente, TipoPaciente tipoPaciente, Sexo sexo, Estacivil estacivil, Ocupacion ocupacion, Distrito distrito, Instruccion instruccion, String nombre1, String apPaterno, String apMaterno, Date fechaNacimiento, Date fechaIngreso, String direccion) {
        this.codPaciente = codPaciente;
        this.tipoPaciente = tipoPaciente;
        this.sexo = sexo;
        this.estacivil = estacivil;
        this.ocupacion = ocupacion;
        this.distrito = distrito;
        this.instruccion = instruccion;
        this.nombre1 = nombre1;
        this.apPaterno = apPaterno;
        this.apMaterno = apMaterno;
        this.fechaNacimiento = fechaNacimiento;
        this.fechaIngreso = fechaIngreso;
        this.direccion = direccion;
    }
    public Paciente(String codPaciente, TipoPaciente tipoPaciente, Sexo sexo, Estacivil estacivil, Ocupacion ocupacion, Distrito distrito, Instruccion instruccion, String nombre1, String nombre2, String apPaterno, String apMaterno, Date fechaNacimiento, Date fechaIngreso, String direccion, String telefono, String email, byte[] foto, Character estado, String dni, Set<Venta> ventas) {
       this.codPaciente = codPaciente;
       this.tipoPaciente = tipoPaciente;
       this.sexo = sexo;
       this.estacivil = estacivil;
       this.ocupacion = ocupacion;
       this.distrito = distrito;
       this.instruccion = instruccion;
       this.nombre1 = nombre1;
       this.nombre2 = nombre2;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaIngreso = fechaIngreso;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.foto = foto;
       this.estado = estado;
       this.dni = dni;
       this.ventas = ventas;
    }
   
     @Id 
    
    @Column(name="cod_paciente", unique=true, nullable=false, length=11)
    public String getCodPaciente() {
        return this.codPaciente;
    }
    
    public void setCodPaciente(String codPaciente) {
        this.codPaciente = codPaciente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_paciente", nullable=false)
    public TipoPaciente getTipoPaciente() {
        return this.tipoPaciente;
    }
    
    public void setTipoPaciente(TipoPaciente tipoPaciente) {
        this.tipoPaciente = tipoPaciente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_sexo", nullable=false)
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_estacivil", nullable=false)
    public Estacivil getEstacivil() {
        return this.estacivil;
    }
    
    public void setEstacivil(Estacivil estacivil) {
        this.estacivil = estacivil;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_ocupacion", nullable=false)
    public Ocupacion getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(Ocupacion ocupacion) {
        this.ocupacion = ocupacion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_distrito", nullable=false)
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_instruccion", nullable=false)
    public Instruccion getInstruccion() {
        return this.instruccion;
    }
    
    public void setInstruccion(Instruccion instruccion) {
        this.instruccion = instruccion;
    }
    
    @Column(name="nombre1", nullable=false, length=45)
    public String getNombre1() {
        return this.nombre1;
    }
    
    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }
    
    @Column(name="nombre2", length=45)
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }
    
    @Column(name="ap_paterno", nullable=false, length=45)
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    
    @Column(name="ap_materno", nullable=false, length=45)
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_nacimiento", nullable=false, length=19)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_ingreso", nullable=false, length=19)
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    
    @Column(name="direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="foto")
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    
    @Column(name="dni", length=11)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


