package com.raitcon.hibernate.bean;
// Generated 23/04/2016 11:00:37 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parametros generated by hbm2java
 */
@Entity
@Table(name="parametros"
    ,catalog="db_laboratorio"
)
public class Parametros  implements java.io.Serializable {


     private Integer idParametros;
     private String razonSocial;
     private String sucursal;
     private String ruc;
     private String direccion;
     private String empresacol;
     private String telefono;
     private String email;
     private String site;
     private Integer igv;
     private Character estado;

    public Parametros() {
    }

	
    public Parametros(String razonSocial, String sucursal, String ruc) {
        this.razonSocial = razonSocial;
        this.sucursal = sucursal;
        this.ruc = ruc;
    }
    public Parametros(String razonSocial, String sucursal, String ruc, String direccion, String empresacol, String telefono, String email, String site, Integer igv, Character estado) {
       this.razonSocial = razonSocial;
       this.sucursal = sucursal;
       this.ruc = ruc;
       this.direccion = direccion;
       this.empresacol = empresacol;
       this.telefono = telefono;
       this.email = email;
       this.site = site;
       this.igv = igv;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_parametros", unique=true, nullable=false)
    public Integer getIdParametros() {
        return this.idParametros;
    }
    
    public void setIdParametros(Integer idParametros) {
        this.idParametros = idParametros;
    }
    
    @Column(name="razon_social", nullable=false, length=45)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    
    @Column(name="sucursal", nullable=false, length=45)
    public String getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(String sucursal) {
        this.sucursal = sucursal;
    }
    
    @Column(name="ruc", nullable=false, length=11)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    
    @Column(name="direccion", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="empresacol", length=45)
    public String getEmpresacol() {
        return this.empresacol;
    }
    
    public void setEmpresacol(String empresacol) {
        this.empresacol = empresacol;
    }
    
    @Column(name="telefono", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="site", length=60)
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    
    @Column(name="igv")
    public Integer getIgv() {
        return this.igv;
    }
    
    public void setIgv(Integer igv) {
        this.igv = igv;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


