package com.raitcon.hibernate.bean;
// Generated 23/04/2016 11:00:37 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,catalog="db_laboratorio"
)
public class Personal  implements java.io.Serializable {


     private String codPersonal;
     private Sexo sexo;
     private Ocupacion ocupacion;
     private String apPaterno;
     private String apMaterno;
     private String nombres;
     private Date fechaNacimiento;
     private String estadoCivil;
     private String especialidad;
     private String mail;
     private String telefono;
     private String direccion;
     private String dni;
     private char estado;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Personal() {
    }

	
    public Personal(String codPersonal, Sexo sexo, Ocupacion ocupacion, String apPaterno, String apMaterno, String nombres, Date fechaNacimiento, String estadoCivil, String mail, String direccion, String dni, char estado) {
        this.codPersonal = codPersonal;
        this.sexo = sexo;
        this.ocupacion = ocupacion;
        this.apPaterno = apPaterno;
        this.apMaterno = apMaterno;
        this.nombres = nombres;
        this.fechaNacimiento = fechaNacimiento;
        this.estadoCivil = estadoCivil;
        this.mail = mail;
        this.direccion = direccion;
        this.dni = dni;
        this.estado = estado;
    }
    public Personal(String codPersonal, Sexo sexo, Ocupacion ocupacion, String apPaterno, String apMaterno, String nombres, Date fechaNacimiento, String estadoCivil, String especialidad, String mail, String telefono, String direccion, String dni, char estado, Set<Venta> ventas) {
       this.codPersonal = codPersonal;
       this.sexo = sexo;
       this.ocupacion = ocupacion;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.nombres = nombres;
       this.fechaNacimiento = fechaNacimiento;
       this.estadoCivil = estadoCivil;
       this.especialidad = especialidad;
       this.mail = mail;
       this.telefono = telefono;
       this.direccion = direccion;
       this.dni = dni;
       this.estado = estado;
       this.ventas = ventas;
    }
   
     @Id 
    
    @Column(name="cod_personal", unique=true, nullable=false, length=16)
    public String getCodPersonal() {
        return this.codPersonal;
    }
    
    public void setCodPersonal(String codPersonal) {
        this.codPersonal = codPersonal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_sexo", nullable=false)
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_ocupacion", nullable=false)
    public Ocupacion getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(Ocupacion ocupacion) {
        this.ocupacion = ocupacion;
    }
    
    @Column(name="ap_paterno", nullable=false, length=80)
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    
    @Column(name="ap_materno", nullable=false, length=80)
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    
    @Column(name="nombres", nullable=false, length=80)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
    @Column(name="estado_civil", nullable=false, length=45)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    
    @Column(name="especialidad", length=45)
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    
    @Column(name="mail", nullable=false, length=45)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    
    @Column(name="telefono", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="direccion", nullable=false, length=80)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="dni", nullable=false, length=16)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personal")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


