package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,catalog="db_laboratorio"
)
public class Personal  implements java.io.Serializable {


     private String codPersonal;
     private Ocupacion ocupacion;
     private String apPaterno;
     private String apMaterno;
     private String nombres;
     private Date fechaNacimiento;
     private Character sexo;
     private String estadoCivil;
     private String especialidad;
     private String mail;
     private String telefono;
     private String direccion;
     private String dni;
     private Character estado;

    public Personal() {
    }

    public Personal(String codPersonal, Ocupacion ocupacion, String apPaterno, String apMaterno, String nombres, Date fechaNacimiento, Character sexo, String estadoCivil, String especialidad, String mail, String telefono, String direccion, String dni,Character state) {
       this.codPersonal = codPersonal;
       this.ocupacion = ocupacion;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.nombres = nombres;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.especialidad = especialidad;
       this.mail = mail;
       this.telefono = telefono;
       this.direccion = direccion;
       this.dni = dni;
       this.estado=state;
    }
   
     @Id 
    
    @Column(name="cod_personal", unique=true, nullable=false, length=16)
    public String getCodPersonal() {
        return this.codPersonal;
    }
    
    public void setCodPersonal(String codPersonal) {
        this.codPersonal = codPersonal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_ocupacion", nullable=false)
    public Ocupacion getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(Ocupacion ocupacion) {
        this.ocupacion = ocupacion;
    }
    
    @Column(name="ap_paterno", nullable=false, length=80)
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }
    
    @Column(name="ap_materno", nullable=false, length=80)
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }
    
    @Column(name="nombres", nullable=false, length=80)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
    @Column(name="sexo", nullable=false, length=1)
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="estado_civil", nullable=false, length=45)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    
    @Column(name="especialidad", nullable=true, length=45)
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    
    @Column(name="mail", nullable=false, length=45)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    
    @Column(name="telefono", nullable=true, length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="direccion", nullable=false, length=80)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="dni", nullable=false, length=16)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    
    
    @Column(name="estado", nullable=false, length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character state) {
        this.estado = state;
    }




}


