package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="db_laboratorio"
    , uniqueConstraints = @UniqueConstraint(columnNames="ruc") 
)
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private Distrito distrito;
     private String ruc;
     private String razonSocial;
     private String telefono;
     private String direccion;
     private String site;
     private String email;
     private String contacto;
     private Character estado;
     private Set<Insumo> insumos = new HashSet<Insumo>(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor, String ruc) {
        this.idProveedor = idProveedor;
        this.ruc = ruc;
    }
    public Proveedor(int idProveedor, Distrito distrito, String ruc, String razonSocial, String telefono, String direccion, String site, String email, String contacto, Character estado, Set<Insumo> insumos) {
       this.idProveedor = idProveedor;
       this.distrito = distrito;
       this.ruc = ruc;
       this.razonSocial = razonSocial;
       this.telefono = telefono;
       this.direccion = direccion;
       this.site = site;
       this.email = email;
       this.contacto = contacto;
       this.estado = estado;
       this.insumos = insumos;
    }
   
     @Id 
    
    @Column(name="id_proveedor", unique=true, nullable=false)
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_distrito")
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    
    @Column(name="ruc", unique=true, nullable=false, length=11)
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    
    @Column(name="razon_social", length=60)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    
    @Column(name="telefono", length=15)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="direccion", length=60)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="site", length=60)
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    
    @Column(name="email", length=55)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="contacto", length=60)
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Insumo> getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set<Insumo> insumos) {
        this.insumos = insumos;
    }




}


