package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:53:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,catalog="db_laboratorio"
)
public class Provincia  implements java.io.Serializable {


     private int codProvincia;
     private int codDepa;
     private String desProvincia;
     private Set<Distrito> distritos = new HashSet<Distrito>(0);

    public Provincia() {
    }

	
    public Provincia(int codProvincia, int codDepa, String desProvincia) {
        this.codProvincia = codProvincia;
        this.codDepa = codDepa;
        this.desProvincia = desProvincia;
    }
    public Provincia(int codProvincia, int codDepa, String desProvincia, Set<Distrito> distritos) {
       this.codProvincia = codProvincia;
       this.codDepa = codDepa;
       this.desProvincia = desProvincia;
       this.distritos = distritos;
    }
   
     @Id 
    
    @Column(name="cod_provincia", unique=true, nullable=false)
    public int getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(int codProvincia) {
        this.codProvincia = codProvincia;
    }
    
    @Column(name="cod_depa", nullable=false)
    public int getCodDepa() {
        return this.codDepa;
    }
    
    public void setCodDepa(int codDepa) {
        this.codDepa = codDepa;
    }
    
    @Column(name="des_provincia", nullable=false, length=100)
    public String getDesProvincia() {
        return this.desProvincia;
    }
    
    public void setDesProvincia(String desProvincia) {
        this.desProvincia = desProvincia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="provincia")
    public Set<Distrito> getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set<Distrito> distritos) {
        this.distritos = distritos;
    }




}


