package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,catalog="db_laboratorio"
)
public class Provincia  implements java.io.Serializable {


     private int codProvincia;
     private Departamento departamento;
     private String desProvincia;
     private Set<Distrito> distritos = new HashSet<Distrito>(0);
     private Set<Distrito> distritos_1 = new HashSet<Distrito>(0);

    public Provincia() {
    }

	
    public Provincia(int codProvincia, Departamento departamento, String desProvincia) {
        this.codProvincia = codProvincia;
        this.departamento = departamento;
        this.desProvincia = desProvincia;
    }
    public Provincia(int codProvincia, Departamento departamento, String desProvincia, Set<Distrito> distritos, Set<Distrito> distritos_1) {
       this.codProvincia = codProvincia;
       this.departamento = departamento;
       this.desProvincia = desProvincia;
       this.distritos = distritos;
       this.distritos_1 = distritos_1;
    }
   
     @Id 
    
    @Column(name="cod_provincia", unique=true, nullable=false)
    public int getCodProvincia() {
        return this.codProvincia;
    }
    
    public void setCodProvincia(int codProvincia) {
        this.codProvincia = codProvincia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_depa", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    
    @Column(name="des_provincia", nullable=false, length=100)
    public String getDesProvincia() {
        return this.desProvincia;
    }
    
    public void setDesProvincia(String desProvincia) {
        this.desProvincia = desProvincia;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="provincia")
    public Set<Distrito> getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set<Distrito> distritos) {
        this.distritos = distritos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="provincia")
    public Set<Distrito> getDistritos_1() {
        return this.distritos_1;
    }
    
    public void setDistritos_1(Set<Distrito> distritos_1) {
        this.distritos_1 = distritos_1;
    }




}


