package com.raitcon.hibernate.bean;
// Generated 23/04/2016 11:00:37 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PruebaValRef generated by hbm2java
 */
@Entity
@Table(name="prueba_val_ref"
    ,catalog="db_laboratorio"
)
public class PruebaValRef  implements java.io.Serializable {


     private Integer idPruebaValRef;
     private ValRef valRef;
     private Prueba prueba;
     private BigDecimal desde;
     private BigDecimal hasta;
     private BigDecimal valRefMin;
     private BigDecimal valorRefMax;
     private String valRefText;
     private Character estado;

    public PruebaValRef() {
    }

    public PruebaValRef(ValRef valRef, Prueba prueba, BigDecimal desde, BigDecimal hasta, BigDecimal valRefMin, BigDecimal valorRefMax, String valRefText, Character estado) {
       this.valRef = valRef;
       this.prueba = prueba;
       this.desde = desde;
       this.hasta = hasta;
       this.valRefMin = valRefMin;
       this.valorRefMax = valorRefMax;
       this.valRefText = valRefText;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_prueba_val_ref", unique=true, nullable=false)
    public Integer getIdPruebaValRef() {
        return this.idPruebaValRef;
    }
    
    public void setIdPruebaValRef(Integer idPruebaValRef) {
        this.idPruebaValRef = idPruebaValRef;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_valor_ref")
    public ValRef getValRef() {
        return this.valRef;
    }
    
    public void setValRef(ValRef valRef) {
        this.valRef = valRef;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_prueba")
    public Prueba getPrueba() {
        return this.prueba;
    }
    
    public void setPrueba(Prueba prueba) {
        this.prueba = prueba;
    }
    
    @Column(name="desde", precision=9)
    public BigDecimal getDesde() {
        return this.desde;
    }
    
    public void setDesde(BigDecimal desde) {
        this.desde = desde;
    }
    
    @Column(name="hasta", precision=9)
    public BigDecimal getHasta() {
        return this.hasta;
    }
    
    public void setHasta(BigDecimal hasta) {
        this.hasta = hasta;
    }
    
    @Column(name="val_ref_min", precision=9)
    public BigDecimal getValRefMin() {
        return this.valRefMin;
    }
    
    public void setValRefMin(BigDecimal valRefMin) {
        this.valRefMin = valRefMin;
    }
    
    @Column(name="valor_ref_max", precision=9)
    public BigDecimal getValorRefMax() {
        return this.valorRefMax;
    }
    
    public void setValorRefMax(BigDecimal valorRefMax) {
        this.valorRefMax = valorRefMax;
    }
    
    @Column(name="val_ref_text", length=400)
    public String getValRefText() {
        return this.valRefText;
    }
    
    public void setValRefText(String valRefText) {
        this.valRefText = valRefText;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


