package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Religion generated by hbm2java
 */
@Entity
@Table(name="religion"
    ,catalog="db_laboratorio"
)
public class Religion  implements java.io.Serializable {


     private int codReligion;
     private String descripcion;

    public Religion() {
    }

	
    public Religion(int codReligion) {
        this.codReligion = codReligion;
    }
    public Religion(int codReligion, String descripcion) {
       this.codReligion = codReligion;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="cod_religion", unique=true, nullable=false)
    public int getCodReligion() {
        return this.codReligion;
    }
    
    public void setCodReligion(int codReligion) {
        this.codReligion = codReligion;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


