package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol"
    ,catalog="db_laboratorio"
)
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String descripcion;
     private String state;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<RolesAccion> rolesAccions = new HashSet<RolesAccion>(0);

    public Rol() {
    }
    
    public Rol(int idRol) {
        this.idRol=idRol;
    }

	
    public Rol(String descripcion) {
        this.descripcion = descripcion;
    }
    public Rol(String descripcion, String state, Set<Usuario> usuarios, Set<RolesAccion> rolesAccions) {
       this.descripcion = descripcion;
       this.state = state;
       this.usuarios = usuarios;
       this.rolesAccions = rolesAccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_rol", unique=true, nullable=false)
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="state", length=1)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="rol")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="rol")
    public Set<RolesAccion> getRolesAccions() {
        return this.rolesAccions;
    }
    
    public void setRolesAccions(Set<RolesAccion> rolesAccions) {
        this.rolesAccions = rolesAccions;
    }




}


