package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolesAccion generated by hbm2java
 */
@Entity
@Table(name="roles_accion"
    ,catalog="db_laboratorio"
)
public class RolesAccion  implements java.io.Serializable {


     private Integer idRolesAccion;
     private Accion accion;
     private Menu menu;
     private Rol rol;

    public RolesAccion() {
    }

    public RolesAccion(Accion accion, Menu menu, Rol rol) {
       this.accion = accion;
       this.menu = menu;
       this.rol = rol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_roles_accion", unique=true, nullable=false)
    public Integer getIdRolesAccion() {
        return this.idRolesAccion;
    }
    
    public void setIdRolesAccion(Integer idRolesAccion) {
        this.idRolesAccion = idRolesAccion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_accion", nullable=false)
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_menu", nullable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


