package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name="sexo"
    ,catalog="db_laboratorio"
)
public class Sexo  implements java.io.Serializable {


     private char codSexo;
     private String descripcion;
     private Integer peso;
     private Set<ValRef> valRefs = new HashSet<ValRef>(0);
     private Set<ValRef> valRefs_1 = new HashSet<ValRef>(0);
     private Set<Personal> personals = new HashSet<Personal>(0);
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);

    public Sexo() {
    }

	
    public Sexo(char codSexo, String descripcion) {
        this.codSexo = codSexo;
        this.descripcion = descripcion;
    }
    public Sexo(char codSexo, String descripcion, Integer peso, Set<ValRef> valRefs, Set<ValRef> valRefs_1, Set<Personal> personals, Set<Paciente> pacientes) {
       this.codSexo = codSexo;
       this.descripcion = descripcion;
       this.peso = peso;
       this.valRefs = valRefs;
       this.valRefs_1 = valRefs_1;
       this.personals = personals;
       this.pacientes = pacientes;
    }
   
     @Id 
    
    @Column(name="cod_sexo", unique=true, nullable=false, length=1)
    public char getCodSexo() {
        return this.codSexo;
    }
    
    public void setCodSexo(char codSexo) {
        this.codSexo = codSexo;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="peso")
    public Integer getPeso() {
        return this.peso;
    }
    
    public void setPeso(Integer peso) {
        this.peso = peso;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sexo")
    public Set<ValRef> getValRefs() {
        return this.valRefs;
    }
    
    public void setValRefs(Set<ValRef> valRefs) {
        this.valRefs = valRefs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sexo")
    public Set<ValRef> getValRefs_1() {
        return this.valRefs_1;
    }
    
    public void setValRefs_1(Set<ValRef> valRefs_1) {
        this.valRefs_1 = valRefs_1;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sexo")
    public Set<Personal> getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set<Personal> personals) {
        this.personals = personals;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sexo")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }




}


