package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubDetExamen generated by hbm2java
 */
@Entity
@Table(name="sub_det_examen"
    ,catalog="db_laboratorio"
)
public class SubDetExamen  implements java.io.Serializable {


     private int idsubdetalleExamen;
     private DetalleExamen detalleExamen;
     private String descripcion;

    public SubDetExamen() {
    }

	
    public SubDetExamen(int idsubdetalleExamen, DetalleExamen detalleExamen) {
        this.idsubdetalleExamen = idsubdetalleExamen;
        this.detalleExamen = detalleExamen;
    }
    public SubDetExamen(int idsubdetalleExamen, DetalleExamen detalleExamen, String descripcion) {
       this.idsubdetalleExamen = idsubdetalleExamen;
       this.detalleExamen = detalleExamen;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="idsubdetalle_examen", unique=true, nullable=false)
    public int getIdsubdetalleExamen() {
        return this.idsubdetalleExamen;
    }
    
    public void setIdsubdetalleExamen(int idsubdetalleExamen) {
        this.idsubdetalleExamen = idsubdetalleExamen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="iddetalle_examen", nullable=false)
    public DetalleExamen getDetalleExamen() {
        return this.detalleExamen;
    }
    
    public void setDetalleExamen(DetalleExamen detalleExamen) {
        this.detalleExamen = detalleExamen;
    }
    
    @Column(name="descripcion", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


