package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubMenu generated by hbm2java
 */
@Entity
@Table(name="sub_menu"
    ,catalog="db_laboratorio"
)
public class SubMenu  implements java.io.Serializable {


     private Integer idSubMenu;
     private Menu menu;
     private String descripcion;
     private Character state;
     private String pagina;

    public SubMenu() {
    }

	
    public SubMenu(Menu menu, String descripcion, String pagina) {
        this.menu = menu;
        this.descripcion = descripcion;
        this.pagina = pagina;
    }
    public SubMenu(Menu menu, String descripcion, Character state, String pagina) {
       this.menu = menu;
       this.descripcion = descripcion;
       this.state = state;
       this.pagina = pagina;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_sub_menu", unique=true, nullable=false)
    public Integer getIdSubMenu() {
        return this.idSubMenu;
    }
    
    public void setIdSubMenu(Integer idSubMenu) {
        this.idSubMenu = idSubMenu;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_menu", nullable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="state", length=1)
    public Character getState() {
        return this.state;
    }
    
    public void setState(Character state) {
        this.state = state;
    }
    
    @Column(name="pagina", nullable=false, length=45)
    public String getPagina() {
        return this.pagina;
    }
    
    public void setPagina(String pagina) {
        this.pagina = pagina;
    }




}


