package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoInsumo generated by hbm2java
 */
@Entity
@Table(name="tipo_insumo"
    ,catalog="db_laboratorio"
)
public class TipoInsumo  implements java.io.Serializable {


     private int idTipoInsumo;
     private String descripcion;
     private Character estado;
     private String numSerie;
     private Integer idAlmacen;
     private Date fechaVencimiento;
     private Set<Insumo> insumos = new HashSet<Insumo>(0);

    public TipoInsumo() {
    }

	
    public TipoInsumo(int idTipoInsumo) {
        this.idTipoInsumo = idTipoInsumo;
    }
    public TipoInsumo(int idTipoInsumo, String descripcion, Character estado, String numSerie, Integer idAlmacen, Date fechaVencimiento, Set<Insumo> insumos) {
       this.idTipoInsumo = idTipoInsumo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.numSerie = numSerie;
       this.idAlmacen = idAlmacen;
       this.fechaVencimiento = fechaVencimiento;
       this.insumos = insumos;
    }
   
     @Id 
    
    @Column(name="id_tipo_insumo", unique=true, nullable=false)
    public int getIdTipoInsumo() {
        return this.idTipoInsumo;
    }
    
    public void setIdTipoInsumo(int idTipoInsumo) {
        this.idTipoInsumo = idTipoInsumo;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    
    @Column(name="num_serie", length=45)
    public String getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }
    
    @Column(name="id_almacen")
    public Integer getIdAlmacen() {
        return this.idAlmacen;
    }
    
    public void setIdAlmacen(Integer idAlmacen) {
        this.idAlmacen = idAlmacen;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_vencimiento", length=19)
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoInsumo")
    public Set<Insumo> getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set<Insumo> insumos) {
        this.insumos = insumos;
    }




}


