package com.raitcon.hibernate.bean;
// Generated 23/04/2016 06:58:33 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoPaciente generated by hbm2java
 */
@Entity
@Table(name="tipo_paciente"
    ,catalog="db_laboratorio"
)
public class TipoPaciente  implements java.io.Serializable {


     private int idTipoPaciente;
     private String descripcion;

    public TipoPaciente() {
    }

    public TipoPaciente(int idTipoPaciente, String descripcion) {
       this.idTipoPaciente = idTipoPaciente;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="id_tipo_paciente", unique=true, nullable=false)
    public int getIdTipoPaciente() {
        return this.idTipoPaciente;
    }
    
    public void setIdTipoPaciente(int idTipoPaciente) {
        this.idTipoPaciente = idTipoPaciente;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


