package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPersona generated by hbm2java
 */
@Entity
@Table(name="tipo_persona"
    ,catalog="db_laboratorio"
)
public class TipoPersona  implements java.io.Serializable {


     private int idTipoPersona;
     private String descripcion;
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);
     private Set<Paciente> pacientes_1 = new HashSet<Paciente>(0);

    public TipoPersona() {
    }

	
    public TipoPersona(int idTipoPersona, String descripcion) {
        this.idTipoPersona = idTipoPersona;
        this.descripcion = descripcion;
    }
    public TipoPersona(int idTipoPersona, String descripcion, Set<Paciente> pacientes, Set<Paciente> pacientes_1) {
       this.idTipoPersona = idTipoPersona;
       this.descripcion = descripcion;
       this.pacientes = pacientes;
       this.pacientes_1 = pacientes_1;
    }
   
     @Id 
    
    @Column(name="id_tipo_persona", unique=true, nullable=false)
    public int getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(int idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoPersona")
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoPersona")
    public Set<Paciente> getPacientes_1() {
        return this.pacientes_1;
    }
    
    public void setPacientes_1(Set<Paciente> pacientes_1) {
        this.pacientes_1 = pacientes_1;
    }




}


