package com.raitcon.hibernate.bean;
// Generated 23/04/2016 06:58:33 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoResultado generated by hbm2java
 */
@Entity
@Table(name="tipo_resultado"
    ,catalog="db_laboratorio"
)
public class TipoResultado  implements java.io.Serializable {


     private Integer idTipoResultado;
     private String descripcion;
     private Set<Prueba> pruebas = new HashSet<Prueba>(0);

    public TipoResultado() {
    }

	
    public TipoResultado(String descripcion) {
        this.descripcion = descripcion;
    }
    public TipoResultado(String descripcion, Set<Prueba> pruebas) {
       this.descripcion = descripcion;
       this.pruebas = pruebas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_tipo_resultado", unique=true, nullable=false)
    public Integer getIdTipoResultado() {
        return this.idTipoResultado;
    }
    
    public void setIdTipoResultado(Integer idTipoResultado) {
        this.idTipoResultado = idTipoResultado;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoResultado")
    public Set<Prueba> getPruebas() {
        return this.pruebas;
    }
    
    public void setPruebas(Set<Prueba> pruebas) {
        this.pruebas = pruebas;
    }




}


