package com.raitcon.hibernate.bean;
// Generated 23/04/2016 11:00:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoExamen generated by hbm2java
 */
@Entity
@Table(name="tipo_examen"
    ,catalog="db_laboratorio"
)
public class TipoExamen  implements java.io.Serializable {


     private int idTipoExamen;
     private String descripcion;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public TipoExamen() {
    }

	
    public TipoExamen(int idTipoExamen) {
        this.idTipoExamen = idTipoExamen;
    }
    public TipoExamen(int idTipoExamen, String descripcion, Set<Examen> examens) {
       this.idTipoExamen = idTipoExamen;
       this.descripcion = descripcion;
       this.examens = examens;
    }
   
     @Id 
    
    @Column(name="id_tipo_examen", unique=true, nullable=false)
    public int getIdTipoExamen() {
        return this.idTipoExamen;
    }
    
    public void setIdTipoExamen(int idTipoExamen) {
        this.idTipoExamen = idTipoExamen;
    }
    
    @Column(name="descripcion", length=60)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoExamen")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }




}


