package com.raitcon.hibernate.bean;
// Generated 09/05/2016 10:48:05 PM by Hibernate Tools 3.2.1.GA



import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidMedida generated by hbm2java
 */
@Entity
@Table(name="unid_medida"
    ,catalog="db_laboratorio"
)
public class UnidMedida  implements java.io.Serializable {


     private int idUnidMedida;
     private String descripcion;
     private Character estado;
     private Set<Prueba> pruebas = new HashSet<Prueba>(0);
     private Set<Insumo> insumos = new HashSet<Insumo>(0);
     private Set<Prueba> pruebas_1 = new HashSet<Prueba>(0);

    public UnidMedida() {
    }

	
    public UnidMedida(int idUnidMedida) {
        this.idUnidMedida = idUnidMedida;
    }
    public UnidMedida(int idUnidMedida, String descripcion, Character estado, Set<Prueba> pruebas, Set<Insumo> insumos, Set<Prueba> pruebas_1) {
       this.idUnidMedida = idUnidMedida;
       this.descripcion = descripcion;
       this.estado = estado;
       this.pruebas = pruebas;
       this.insumos = insumos;
       this.pruebas_1 = pruebas_1;
    }
   
     @Id 
    
    @Column(name="id_unid_medida", unique=true, nullable=false)
    public int getIdUnidMedida() {
        return this.idUnidMedida;
    }
    
    public void setIdUnidMedida(int idUnidMedida) {
        this.idUnidMedida = idUnidMedida;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="estado", length=1)
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unidMedida")
    public Set<Prueba> getPruebas() {
        return this.pruebas;
    }
    
    public void setPruebas(Set<Prueba> pruebas) {
        this.pruebas = pruebas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unidMedida")
    public Set<Insumo> getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set<Insumo> insumos) {
        this.insumos = insumos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unidMedida")
    public Set<Prueba> getPruebas_1() {
        return this.pruebas_1;
    }
    
    public void setPruebas_1(Set<Prueba> pruebas_1) {
        this.pruebas_1 = pruebas_1;
    }




}


