package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="db_laboratorio"
)
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Rol rol;
     private String nombre;
     private String apellidos;
     private String login;
     private String password;
     private Character state;

    public Usuario() {
    }

	
    public Usuario(Rol rol, String login, String password) {
        this.rol = rol;
        this.login = login;
        this.password = password;
    }
    public Usuario(Rol rol, String nombre, String apellidos, String login, String password, Character state) {
       this.rol = rol;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.login = login;
       this.password = password;
       this.state = state;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idusuario", unique=true, nullable=false)
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="apellidos", length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="login", nullable=false, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="password", nullable=false, length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="state", length=1)
    public Character getState() {
        return this.state;
    }
    
    public void setState(Character state) {
        this.state = state;
    }




}


