package com.raitcon.hibernate.bean;
// Generated 25/03/2016 09:41:30 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ValoresNormales generated by hbm2java
 */
@Entity
@Table(name="valores_normales"
    ,catalog="db_laboratorio"
)
public class ValoresNormales  implements java.io.Serializable {


     private Integer idvaloresNormales;
     private String descripcion;

    public ValoresNormales() {
    }

    public ValoresNormales(String descripcion) {
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idvalores_normales", unique=true, nullable=false)
    public Integer getIdvaloresNormales() {
        return this.idvaloresNormales;
    }
    
    public void setIdvaloresNormales(Integer idvaloresNormales) {
        this.idvaloresNormales = idvaloresNormales;
    }
    
    @Column(name="descripcion", length=80)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


