package com.raitcon.hibernate.bean;
// Generated 23/04/2016 11:00:37 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ValRef generated by hbm2java
 */
@Entity
@Table(name="val_ref"
    ,catalog="db_laboratorio"
)
public class ValRef  implements java.io.Serializable {


     private int idValRef;
     private String descripcion;
     private Set<PruebaValRef> pruebaValRefs = new HashSet<PruebaValRef>(0);
     private Set<PruebaValRef> pruebaValRefs_1 = new HashSet<PruebaValRef>(0);

    public ValRef() {
    }

	
    public ValRef(int idValRef) {
        this.idValRef = idValRef;
    }
    public ValRef(int idValRef, String descripcion, Set<PruebaValRef> pruebaValRefs, Set<PruebaValRef> pruebaValRefs_1) {
       this.idValRef = idValRef;
       this.descripcion = descripcion;
       this.pruebaValRefs = pruebaValRefs;
       this.pruebaValRefs_1 = pruebaValRefs_1;
    }
   
     @Id 
    
    @Column(name="id_val_ref", unique=true, nullable=false)
    public int getIdValRef() {
        return this.idValRef;
    }
    
    public void setIdValRef(int idValRef) {
        this.idValRef = idValRef;
    }
    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="valRef")
    public Set<PruebaValRef> getPruebaValRefs() {
        return this.pruebaValRefs;
    }
    
    public void setPruebaValRefs(Set<PruebaValRef> pruebaValRefs) {
        this.pruebaValRefs = pruebaValRefs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="valRef")
    public Set<PruebaValRef> getPruebaValRefs_1() {
        return this.pruebaValRefs_1;
    }
    
    public void setPruebaValRefs_1(Set<PruebaValRef> pruebaValRefs_1) {
        this.pruebaValRefs_1 = pruebaValRefs_1;
    }




}


